// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace ModernLife
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Int32 MyProperty;
        Int32 SeedPercent;
        String GetSliderText(Int32 value);
        Microsoft.UI.Xaml.Controls.Slider sliderPop{get;};
    }
}