// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace ModernLife
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainWindow();
        UInt16 RandomPercent;
        UInt16 BoardWidth;
        UInt16 MaxAge;
        Boolean ShowLegend;
        String FPSAverage{ get; };
        String GenerationCount { get; };
        String LiveCount{ get; };
        String GetRandomPercentText(Double value);
        String GetBoardWidthText(Double value);
        Microsoft.UI.Xaml.Controls.Slider sliderRandomPercent{get;};
        Microsoft.UI.Xaml.Controls.Slider sliderBoardWidth{get;};
    }
}