// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace ModernLife
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Int32 SeedPercent;
        Int16 BoardWidth;
        Int32 MaxAge;
        Boolean ShowLegend;
        String GetRandPercentText(Double value);
        String GetBoardWidthText(Double value);
        Microsoft.UI.Xaml.Controls.Slider sliderRandPercent{get;};
        Microsoft.UI.Xaml.Controls.Slider sliderBoardWidth{get;};
    }
}